services:
  MauticPlugin\LeuchtfeuerThemeSwitchingBundle\EventListener\BuilderSubscriber:
    arguments:
      - '@mautic.factory'
    tags:
      - { name: 'kernel.event_subscriber' }

  leuchtfeuer.themeswitching.service:
    class: MauticPlugin\LeuchtfeuerThemeSwitchingBundle\Service\ThemeSwitchingService
    arguments:
      - '@logger'
      - '@parameter_bag'
      - '@mautic.helper.core_parameters'
      - '@doctrine.orm.entity_manager'
      - '@twig'

  MauticPlugin\LeuchtfeuerThemeSwitchingBundle\Controller\ThemeSwitchingController:
    public: true
    autowire: true
    autoconfigure: false
    arguments:
      $themeSwitcher: '@leuchtfeuer.themeswitching.service'
      $factory: '@mautic.factory'





# Optional: remove if not overriding EmailController
#  Mautic\EmailBundle\Controller\EmailController:
#    public: true
#    autowire: true
#    autoconfigure: false
#    arguments:
#      $themeSwitcher: '@leuchtfeuer.themeswitching.service'
